name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Chạy mỗi 12 giờ
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v3
        with:
          github_user_name: DoubleNH25 # Thay DoubleNH25 bằng tên người dùng GitHub của bạn
          outputs: |\
            dist/github-snake.svg\
            dist/github-snake-dark.svg?palette=github-dark
